# Generated by Django 4.2 on 2024-10-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="EMPLOYMENT_STATUS",
            field=models.CharField(
                blank=True,
                choices=[("processing", "processing"), ("accepted", "accepted")],
                max_length=20,
            ),
        ),
    ]
