# Generated by Django 4.2 on 2024-10-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_author_employment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="phone",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
