# Generated by Django 4.2 on 2024-10-14 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_author_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="resume",
            field=models.FileField(upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
