# Generated by Django 4.2 on 2024-10-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_author_resume_alter_author_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="resume",
            field=models.FileField(blank=True, upload_to="resumes/"),
        ),
    ]
