# Generated by Django 4.2 on 2024-10-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_author_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="education",
            field=models.CharField(max_length=225, null=True),
        ),
    ]
