# Generated by Django 4.2 on 2024-10-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="author",
            field=models.ManyToManyField(to="news.author"),
        ),
    ]
