# Generated by Django 4.2 on 2024-10-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="news_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="news.news",
            ),
        ),
    ]
