# Generated by Django 4.2 on 2024-10-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_image_news_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="news_id",
            new_name="news",
        ),
    ]
