# Generated by Django 4.2 on 2024-10-06 10:38

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_rename_news_id_image_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                upload_to=news.models.get_image_filename, verbose_name="image"
            ),
        ),
    ]
