# Generated by Django 4.2 on 2024-10-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="main_image",
            field=models.BooleanField(default=False),
        ),
    ]
